version: "3.7"

services:
  db:
    image: postgres:13-alpine
    container_name: emails_database
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: emails_pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nestjs.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80

    ports:
      - 8080:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data # Persistir los datos de Redis (opcional)

volumes:
  redis-data:
